package selenium;// Generated by Selenium IDE

import org.junit.After;
import org.junit.Before;
import org.junit.Test;
import org.openqa.selenium.By;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.interactions.Actions;

import java.util.HashMap;
import java.util.Map;

public class NewTestTest {
private WebDriver driver;
private Map<String, Object> vars;
JavascriptExecutor js;

@Before
public void setUp() {
  driver = new ChromeDriver();
  js = (JavascriptExecutor) driver;
  vars = new HashMap<String, Object>();
}
@After
public void tearDown() {
  driver.quit();
}
  @Test
  public void newTest() {
    driver.get("https://schneider-russia.com");
    driver.findElement(By.xpath("//a[text()='Розетки']")).click();
    driver.findElement(By.xpath("//a[text()='USB-розетки']")).click();
    driver.findElement(By.xpath("//*[@class='category-item-title'][1]")).click();
    {
      WebElement element = driver.findElement(By.xpath("//*[@class='e-icon-catalog-w']/span"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    driver.findElement(By.xpath("//*[@data-buytext]")).click();
    {
      WebElement element = driver.findElement(By.xpath("//*[@data-buytext]"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    driver.findElement(By.xpath("//a[contains(text(), 'Перейти в корзину')]")).click();
    js.executeScript("window.scrollTo(0,184)");
    driver.findElement(By.xpath("//*[contains(@class, 'btn-count') and contains(@class, 'btn-plus')]")).click();
    driver.findElement(By.xpath("//*[contains(@class, 'btn-delete-item')]")).click();
  }
}
